In [1]:
import pandas as pd

In [2]:
import pandas as pd

data = {
    "Name":["Amit","Priya","Rahul","Sneha","Ravi","Neha"],
    "State":["Karnataka","Tamil Nadu","Karnataka","Kerala","Maharashtra","Karnataka"],
    "Salary":[50000,60000,45000,70000,65000,52000],
    "Department":["IT","HR","IT","Finance","HR","IT"]
}

df = pd.DataFrame(data)

df.to_csv("indian_employees.csv",index=False)

df

    Name        State  Salary Department
0   Amit    Karnataka   50000         IT
1  Priya   Tamil Nadu   60000         HR
2  Rahul    Karnataka   45000         IT
3  Sneha       Kerala   70000    Finance
4   Ravi  Maharashtra   65000         HR
5   Neha    Karnataka   52000         IT

In [3]:
df=pd.read_csv("indian_employees.csv")

df

    Name        State  Salary Department
0   Amit    Karnataka   50000         IT
1  Priya   Tamil Nadu   60000         HR
2  Rahul    Karnataka   45000         IT
3  Sneha       Kerala   70000    Finance
4   Ravi  Maharashtra   65000         HR
5   Neha    Karnataka   52000         IT

In [4]:

print(df.shape)

(6, 4)

In [5]:
print(df.dtypes)

Name          object
State         object
Salary         int64
Department    object
dtype: object

In [6]:
print(df.head(10))

    Name        State  Salary Department
0   Amit    Karnataka   50000         IT
1  Priya   Tamil Nadu   60000         HR
2  Rahul    Karnataka   45000         IT
3  Sneha       Kerala   70000    Finance
4   Ravi  Maharashtra   65000         HR
5   Neha    Karnataka   52000         IT

In [7]:
# Filter employees whose salary is greater than 50000

filtered=df[df["Salary"]>50000]

print(filtered)

    Name        State  Salary Department
1  Priya   Tamil Nadu   60000         HR
3  Sneha       Kerala   70000    Finance
4   Ravi  Maharashtra   65000         HR
5   Neha    Karnataka   52000         IT

In [8]:
# Group employees by state and calculate average salary

group=df.groupby("State")["Salary"].mean()

print(group)

State
Karnataka      49000.0
Kerala         70000.0
Maharashtra    65000.0
Tamil Nadu     60000.0
Name: Salary, dtype: float64

In [9]:
department_info=pd.DataFrame({

"Department":["IT","HR","Finance"],

"Manager":["Kiran","Anita","Suresh"]

})

merged=pd.merge(df,department_info,on="Department")

print(merged)

    Name        State  Salary Department Manager
0   Amit    Karnataka   50000         IT   Kiran
1  Priya   Tamil Nadu   60000         HR   Anita
2  Rahul    Karnataka   45000         IT   Kiran
3  Sneha       Kerala   70000    Finance  Suresh
4   Ravi  Maharashtra   65000         HR   Anita
5   Neha    Karnataka   52000         IT   Kiran

In [10]:
pivot=df.pivot_table(

values="Salary",

index="State",

columns="Department",

aggfunc="mean"

)

print(pivot)

Department   Finance       HR       IT
State
Karnataka        NaN      NaN  49000.0
Kerala       70000.0      NaN      NaN
Maharashtra      NaN  65000.0      NaN
Tamil Nadu       NaN  60000.0      NaN

In [14]:
df.to_csv("cleaned_data.csv",index=False)

In [15]:
df.to_parquet("cleaned_data.parquet")

In [16]:
!pip install pyarrow

Requirement already satisfied: pyarrow in /usr/local/lib/python3.12/dist-packages (18.1.0)

In [17]:
import os

csv_size=os.path.getsize("cleaned_data.csv")

parquet_size=os.path.getsize("cleaned_data.parquet")

print("CSV:",csv_size,"bytes")

print("Parquet:",parquet_size,"bytes")

CSV: 181 bytes
Parquet: 3198 bytes