In [ ]:
# Week 4 Day 3

## Model Serialization — Joblib & Pickle

**Name:** Chaitra MH

### Objective

To train a machine learning model, save it using Joblib and Pickle, load the saved models, and verify that the loaded models produce the same predictions.

In [2]:
import numpy as np
import joblib
import pickle

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [3]:
# load the Iris dataset
iris = load_iris()
X=iris.data
y=iris.target
#display dataset information
print("fetaure shape:", X.shape)
print("Target shape:", y.shape)
print("\n feature names:")
print(iris.target_names)
print("\n Target names:")
print(iris.target_names)

fetaure shape: (150, 4)
Target shape: (150,)

 feature names:
['setosa' 'versicolor' 'virginica']

 Target names:
['setosa' 'versicolor' 'virginica']

In [5]:
# Split the dataset into training and testing data

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training samples:", X_train.shape[0])
print("Testing samples:", X_test.shape[0])

Training samples: 120
Testing samples: 30

In [6]:
#create and train the logistics regression model
model=LogisticRegression(
    max_iter=1000,
    random_state=42
)
model.fit(X_train,y_train)
print("model training completed successfully")

model training completed successfully

In [8]:
#make predications using the original trained model
original_predictions=model.predict(X_test)
#Calculate model accuracy
original_accuracy=accuracy_score(
    y_test,
    original_predictions
)
print("original model accuracy:", original_accuracy)

original model accuracy: 0.9666666666666667

In [9]:
#save the trained model using joblib
joblib.dump(
    model,
    "iris_model_joblib.pk1"
)
print("model saved successfully using joblib")

model saved successfully using joblib

In [10]:
#display files available in the colab environment
import os
print(os.listdir())

['.config', 'iris_model_joblib.pk1', 'sample_data']

In [11]:
#load the saved model using joblib
loaded_joblib_model=joblib.load(
    "iris_model_joblib.pk1"
)
print("joblib model loaded successfully.")

joblib model loaded successfully.

In [13]:
# Make predictions using the loaded Joblib model

joblib_predictions = loaded_joblib_model.predict(
    X_test
)

# Calculate accuracy

joblib_accuracy = accuracy_score(
    y_test,
    joblib_predictions
)

print(
    "Loaded Joblib model accuracy:",
    joblib_accuracy
)

Loaded Joblib model accuracy: 0.9666666666666667

In [15]:
#save the trained model using pickle
with open(
    "iris_model_pickle.pk1",
    "wb"
) as file:
  pickle.dump(
    model,
    file
)
print("model saved successfully using pickle")

model saved successfully using pickle

In [16]:
#load the saved model using pickle
with open(
    "iris_model_pickle.pk1",
    "rb"
) as file:
   loaded_pickle_model= pickle.load(
      file
  )
   print("pickle model loaded succussefully")

pickle model loaded succussefully

In [17]:
# Make predictions using the loaded Pickle model

pickle_predictions = loaded_pickle_model.predict(
    X_test
)

# Calculate accuracy

pickle_accuracy = accuracy_score(
    y_test,
    pickle_predictions
)

print(
    "Loaded Pickle model accuracy:",
    pickle_accuracy
)

Loaded Pickle model accuracy: 0.9666666666666667

In [18]:
# Verify that all models produce the same predictions

joblib_test = np.array_equal(
    original_predictions,
    joblib_predictions
)

pickle_test = np.array_equal(
    original_predictions,
    pickle_predictions
)

print(
    "Original and Joblib predictions are equal:",
    joblib_test
)

print(
    "Original and Pickle predictions are equal:",
    pickle_test
)

# Final test

assert joblib_test, (
    "Joblib predictions do not match."
)

assert pickle_test, (
    "Pickle predictions do not match."
)

print(
    "\nAll serialization tests passed successfully!"
)

Original and Joblib predictions are equal: True
Original and Pickle predictions are equal: True

All serialization tests passed successfully!

In [19]:
# Create a comparison table

results = {
    "Model": [
        "Original Model",
        "Loaded Joblib Model",
        "Loaded Pickle Model"
    ],

    "Accuracy": [
        original_accuracy,
        joblib_accuracy,
        pickle_accuracy
    ]
}

import pandas as pd

results_df = pd.DataFrame(
    results
)

results_df

                 Model  Accuracy
0       Original Model  0.966667
1  Loaded Joblib Model  0.966667
2  Loaded Pickle Model  0.966667

In [21]:
# Create a comparison table

results = {
    "Model": [
        "Original Model",
        "Loaded Joblib Model",
        "Loaded Pickle Model"
    ],

    "Accuracy": [
        original_accuracy,
        joblib_accuracy,
        pickle_accuracy
    ]
}

import pandas as pd

results_df = pd.DataFrame(
    results
)

results_df

                 Model  Accuracy
0       Original Model  0.966667
1  Loaded Joblib Model  0.966667
2  Loaded Pickle Model  0.966667

In [23]:
# Save the trained model using Joblib

joblib.dump(model, "iris_model_joblib.pkl")

print("Joblib model saved successfully.")

Joblib model saved successfully.

In [25]:
import os

print("Joblib file exists:", os.path.exists("iris_model_joblib.pkl"))
print("Pickle file exists:", os.path.exists("iris_model_pickle.pkl"))

Joblib file exists: True
Pickle file exists: False

In [26]:
# Save the trained model using Pickle

with open("iris_model_pickle.pkl", "wb") as file:
    pickle.dump(model, file)

print("Pickle model saved successfully.")

Pickle model saved successfully.

In [27]:
# Compare the sizes of the saved model files

joblib_size = os.path.getsize("iris_model_joblib.pkl")

pickle_size = os.path.getsize("iris_model_pickle.pkl")

print("Joblib file size:", joblib_size, "bytes")

print("Pickle file size:", pickle_size, "bytes")

Joblib file size: 991 bytes
Pickle file size: 837 bytes